/// The entrypoint for the **client** environment.
///
/// Only the components annotated `@client` are hydrated here — the theme
/// toggle, the code-block copy buttons and the sidebar toggle. Everything else
/// on the page is server-rendered HTML that never needs this file to work.
library;

import 'package:jaspr/client.dart';

// Generated by jaspr_builder; do not edit.
import 'main.client.options.dart';

void main() {
  Jaspr.initializeApp(options: defaultClientOptions);
  runApp(const ClientApp());
}
